# Generated by Django 5.2.7 on 2025-12-15 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=70, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten números.', regex='^\\d+$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RFC debe tener 12 a 13 caracteres (letras y números).', regex='^[A-ZÑ&0-9]{12,13}$')])),
                ('es_mayorista', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
