# Generated by Django 5.2.7 on 2025-12-12 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RFC debe tener 12 a 13 caracteres (letras y números).', regex='^[A-ZÑ&0-9]{12,13}$')]),
        ),
    ]
