# Generated by Django 5.2.7 on 2025-12-13 07:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='client_phone',
            new_name='cliente_telefono',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='client_name',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='product',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale',
            new_name='venta',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='change',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sale',
            name='cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='cantidad_pagada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='REALIZADA', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
