# Generated by Django 5.2.7 on 2025-12-14 00:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_address_alter_client_phone_and_more'),
        ('sales', '0002_rename_client_sale_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='fecha',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='venta',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cambio',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cantidad_pagada',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cliente_telefono',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='precio',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='folio',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='quick_client_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='quick_client_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='qty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
