# Generated by Django 5.2.7 on 2025-12-10 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=70)),
                ('apellido_materno', models.CharField(blank=True, max_length=70, null=True)),
                ('rol', models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor')], default='VENDEDOR', max_length=20)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
