# Generated by Django 5.2.7 on 2025-12-15 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_opened', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
